// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pb/kvstore.proto

package kvstorepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ReadMode selects the visibility and coordination cost of Read.
type ReadMode int32

const (
	// READ_MODE_UNSPECIFIED is normalized to READ_MODE_LINEARIZABLE by the server.
	ReadMode_READ_MODE_UNSPECIFIED ReadMode = 0
	// READ_MODE_LOCAL returns the latest state already applied on this node. It
	// does not contact a quorum and may therefore return stale data.
	ReadMode_READ_MODE_LOCAL ReadMode = 1
	// READ_MODE_REVISION returns the value visible at ReadRequest.revision from
	// this node's retained history. It does not perform a ReadIndex round trip.
	ReadMode_READ_MODE_REVISION ReadMode = 2
	// READ_MODE_LINEARIZABLE uses Raft ReadIndex and waits until this node has
	// applied the returned log index before reading the local state machine.
	ReadMode_READ_MODE_LINEARIZABLE ReadMode = 3
)

// Enum value maps for ReadMode.
var (
	ReadMode_name = map[int32]string{
		0: "READ_MODE_UNSPECIFIED",
		1: "READ_MODE_LOCAL",
		2: "READ_MODE_REVISION",
		3: "READ_MODE_LINEARIZABLE",
	}
	ReadMode_value = map[string]int32{
		"READ_MODE_UNSPECIFIED":  0,
		"READ_MODE_LOCAL":        1,
		"READ_MODE_REVISION":     2,
		"READ_MODE_LINEARIZABLE": 3,
	}
)

func (x ReadMode) Enum() *ReadMode {
	p := new(ReadMode)
	*p = x
	return p
}

func (x ReadMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReadMode) Descriptor() protoreflect.EnumDescriptor {
	return file_pb_kvstore_proto_enumTypes[0].Descriptor()
}

func (ReadMode) Type() protoreflect.EnumType {
	return &file_pb_kvstore_proto_enumTypes[0]
}

func (x ReadMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReadMode.Descriptor instead.
func (ReadMode) EnumDescriptor() ([]byte, []int) {
	return file_pb_kvstore_proto_rawDescGZIP(), []int{0}
}

type PutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutRequest) Reset() {
	*x = PutRequest{}
	mi := &file_pb_kvstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutRequest) ProtoMessage() {}

func (x *PutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kvstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutRequest.ProtoReflect.Descriptor instead.
func (*PutRequest) Descriptor() ([]byte, []int) {
	return file_pb_kvstore_proto_rawDescGZIP(), []int{0}
}

func (x *PutRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *PutRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type PutResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Record        *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutResponse) Reset() {
	*x = PutResponse{}
	mi := &file_pb_kvstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutResponse) ProtoMessage() {}

func (x *PutResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kvstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutResponse.ProtoReflect.Descriptor instead.
func (*PutResponse) Descriptor() ([]byte, []int) {
	return file_pb_kvstore_proto_rawDescGZIP(), []int{1}
}

func (x *PutResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_pb_kvstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kvstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_pb_kvstore_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type DeleteResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// record is absent when the key did not exist. Deleting a missing key is an
	// idempotent successful operation and does not advance the logical revision.
	Record        *Record `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteResponse) Reset() {
	*x = DeleteResponse{}
	mi := &file_pb_kvstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResponse) ProtoMessage() {}

func (x *DeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kvstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResponse.ProtoReflect.Descriptor instead.
func (*DeleteResponse) Descriptor() ([]byte, []int) {
	return file_pb_kvstore_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

type ReadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Mode  ReadMode               `protobuf:"varint,2,opt,name=mode,proto3,enum=kvstore.ReadMode" json:"mode,omitempty"`
	// revision must be greater than zero exactly when mode is
	// READ_MODE_REVISION, and must be zero for all other modes.
	Revision      uint64 `protobuf:"varint,3,opt,name=revision,proto3" json:"revision,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRequest) Reset() {
	*x = ReadRequest{}
	mi := &file_pb_kvstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRequest) ProtoMessage() {}

func (x *ReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kvstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRequest.ProtoReflect.Descriptor instead.
func (*ReadRequest) Descriptor() ([]byte, []int) {
	return file_pb_kvstore_proto_rawDescGZIP(), []int{4}
}

func (x *ReadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadRequest) GetMode() ReadMode {
	if x != nil {
		return x.Mode
	}
	return ReadMode_READ_MODE_UNSPECIFIED
}

func (x *ReadRequest) GetRevision() uint64 {
	if x != nil {
		return x.Revision
	}
	return 0
}

type ReadResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Record *Record                `protobuf:"bytes,1,opt,name=record,proto3" json:"record,omitempty"`
	// mode is the normalized mode actually used by the server. In particular,
	// an unspecified request is returned as READ_MODE_LINEARIZABLE.
	Mode ReadMode `protobuf:"varint,2,opt,name=mode,proto3,enum=kvstore.ReadMode" json:"mode,omitempty"`
	// requested_revision is set only for READ_MODE_REVISION.
	RequestedRevision uint64 `protobuf:"varint,3,opt,name=requested_revision,json=requestedRevision,proto3" json:"requested_revision,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ReadResponse) Reset() {
	*x = ReadResponse{}
	mi := &file_pb_kvstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResponse) ProtoMessage() {}

func (x *ReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kvstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResponse.ProtoReflect.Descriptor instead.
func (*ReadResponse) Descriptor() ([]byte, []int) {
	return file_pb_kvstore_proto_rawDescGZIP(), []int{5}
}

func (x *ReadResponse) GetRecord() *Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *ReadResponse) GetMode() ReadMode {
	if x != nil {
		return x.Mode
	}
	return ReadMode_READ_MODE_UNSPECIFIED
}

func (x *ReadResponse) GetRequestedRevision() uint64 {
	if x != nil {
		return x.RequestedRevision
	}
	return 0
}

type Record struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Key            string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value          string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	CreateRevision uint64                 `protobuf:"varint,3,opt,name=create_revision,json=createRevision,proto3" json:"create_revision,omitempty"`
	ModRevision    uint64                 `protobuf:"varint,4,opt,name=mod_revision,json=modRevision,proto3" json:"mod_revision,omitempty"`
	Version        uint64                 `protobuf:"varint,5,opt,name=version,proto3" json:"version,omitempty"`
	Deleted        bool                   `protobuf:"varint,6,opt,name=deleted,proto3" json:"deleted,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_pb_kvstore_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kvstore_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_pb_kvstore_proto_rawDescGZIP(), []int{6}
}

func (x *Record) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Record) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Record) GetCreateRevision() uint64 {
	if x != nil {
		return x.CreateRevision
	}
	return 0
}

func (x *Record) GetModRevision() uint64 {
	if x != nil {
		return x.ModRevision
	}
	return 0
}

func (x *Record) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Record) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      uint64                 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	RaftUrl       string                 `protobuf:"bytes,2,opt,name=raft_url,json=raftUrl,proto3" json:"raft_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_pb_kvstore_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kvstore_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_pb_kvstore_proto_rawDescGZIP(), []int{7}
}

func (x *AddMemberRequest) GetMemberId() uint64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *AddMemberRequest) GetRaftUrl() string {
	if x != nil {
		return x.RaftUrl
	}
	return ""
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      uint64                 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_pb_kvstore_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kvstore_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_pb_kvstore_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveMemberRequest) GetMemberId() uint64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

type MemberChangeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberChangeResponse) Reset() {
	*x = MemberChangeResponse{}
	mi := &file_pb_kvstore_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberChangeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberChangeResponse) ProtoMessage() {}

func (x *MemberChangeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pb_kvstore_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberChangeResponse.ProtoReflect.Descriptor instead.
func (*MemberChangeResponse) Descriptor() ([]byte, []int) {
	return file_pb_kvstore_proto_rawDescGZIP(), []int{9}
}

func (x *MemberChangeResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_pb_kvstore_proto protoreflect.FileDescriptor

const file_pb_kvstore_proto_rawDesc = "" +
	"\n" +
	"\x10pb/kvstore.proto\x12\akvstore\"4\n" +
	"\n" +
	"PutRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"6\n" +
	"\vPutResponse\x12'\n" +
	"\x06record\x18\x01 \x01(\v2\x0f.kvstore.RecordR\x06record\"!\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"9\n" +
	"\x0eDeleteResponse\x12'\n" +
	"\x06record\x18\x01 \x01(\v2\x0f.kvstore.RecordR\x06record\"b\n" +
	"\vReadRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x11.kvstore.ReadModeR\x04mode\x12\x1a\n" +
	"\brevision\x18\x03 \x01(\x04R\brevision\"\x8d\x01\n" +
	"\fReadResponse\x12'\n" +
	"\x06record\x18\x01 \x01(\v2\x0f.kvstore.RecordR\x06record\x12%\n" +
	"\x04mode\x18\x02 \x01(\x0e2\x11.kvstore.ReadModeR\x04mode\x12-\n" +
	"\x12requested_revision\x18\x03 \x01(\x04R\x11requestedRevision\"\xb0\x01\n" +
	"\x06Record\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12'\n" +
	"\x0fcreate_revision\x18\x03 \x01(\x04R\x0ecreateRevision\x12!\n" +
	"\fmod_revision\x18\x04 \x01(\x04R\vmodRevision\x12\x18\n" +
	"\aversion\x18\x05 \x01(\x04R\aversion\x12\x18\n" +
	"\adeleted\x18\x06 \x01(\bR\adeleted\"J\n" +
	"\x10AddMemberRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x04R\bmemberId\x12\x19\n" +
	"\braft_url\x18\x02 \x01(\tR\araftUrl\"2\n" +
	"\x13RemoveMemberRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x04R\bmemberId\"2\n" +
	"\x14MemberChangeResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted*n\n" +
	"\bReadMode\x12\x19\n" +
	"\x15READ_MODE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fREAD_MODE_LOCAL\x10\x01\x12\x16\n" +
	"\x12READ_MODE_REVISION\x10\x02\x12\x1a\n" +
	"\x16READ_MODE_LINEARIZABLE\x10\x032\xab\x01\n" +
	"\aKVStore\x120\n" +
	"\x03Put\x12\x13.kvstore.PutRequest\x1a\x14.kvstore.PutResponse\x129\n" +
	"\x06Delete\x12\x16.kvstore.DeleteRequest\x1a\x17.kvstore.DeleteResponse\x123\n" +
	"\x04Read\x12\x14.kvstore.ReadRequest\x1a\x15.kvstore.ReadResponse2\x9d\x01\n" +
	"\aCluster\x12E\n" +
	"\tAddMember\x12\x19.kvstore.AddMemberRequest\x1a\x1d.kvstore.MemberChangeResponse\x12K\n" +
	"\fRemoveMember\x12\x1c.kvstore.RemoveMemberRequest\x1a\x1d.kvstore.MemberChangeResponseB\x16Z\x14kvstore/pb;kvstorepbb\x06proto3"

var (
	file_pb_kvstore_proto_rawDescOnce sync.Once
	file_pb_kvstore_proto_rawDescData []byte
)

func file_pb_kvstore_proto_rawDescGZIP() []byte {
	file_pb_kvstore_proto_rawDescOnce.Do(func() {
		file_pb_kvstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pb_kvstore_proto_rawDesc), len(file_pb_kvstore_proto_rawDesc)))
	})
	return file_pb_kvstore_proto_rawDescData
}

var file_pb_kvstore_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pb_kvstore_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_pb_kvstore_proto_goTypes = []any{
	(ReadMode)(0),                // 0: kvstore.ReadMode
	(*PutRequest)(nil),           // 1: kvstore.PutRequest
	(*PutResponse)(nil),          // 2: kvstore.PutResponse
	(*DeleteRequest)(nil),        // 3: kvstore.DeleteRequest
	(*DeleteResponse)(nil),       // 4: kvstore.DeleteResponse
	(*ReadRequest)(nil),          // 5: kvstore.ReadRequest
	(*ReadResponse)(nil),         // 6: kvstore.ReadResponse
	(*Record)(nil),               // 7: kvstore.Record
	(*AddMemberRequest)(nil),     // 8: kvstore.AddMemberRequest
	(*RemoveMemberRequest)(nil),  // 9: kvstore.RemoveMemberRequest
	(*MemberChangeResponse)(nil), // 10: kvstore.MemberChangeResponse
}
var file_pb_kvstore_proto_depIdxs = []int32{
	7,  // 0: kvstore.PutResponse.record:type_name -> kvstore.Record
	7,  // 1: kvstore.DeleteResponse.record:type_name -> kvstore.Record
	0,  // 2: kvstore.ReadRequest.mode:type_name -> kvstore.ReadMode
	7,  // 3: kvstore.ReadResponse.record:type_name -> kvstore.Record
	0,  // 4: kvstore.ReadResponse.mode:type_name -> kvstore.ReadMode
	1,  // 5: kvstore.KVStore.Put:input_type -> kvstore.PutRequest
	3,  // 6: kvstore.KVStore.Delete:input_type -> kvstore.DeleteRequest
	5,  // 7: kvstore.KVStore.Read:input_type -> kvstore.ReadRequest
	8,  // 8: kvstore.Cluster.AddMember:input_type -> kvstore.AddMemberRequest
	9,  // 9: kvstore.Cluster.RemoveMember:input_type -> kvstore.RemoveMemberRequest
	2,  // 10: kvstore.KVStore.Put:output_type -> kvstore.PutResponse
	4,  // 11: kvstore.KVStore.Delete:output_type -> kvstore.DeleteResponse
	6,  // 12: kvstore.KVStore.Read:output_type -> kvstore.ReadResponse
	10, // 13: kvstore.Cluster.AddMember:output_type -> kvstore.MemberChangeResponse
	10, // 14: kvstore.Cluster.RemoveMember:output_type -> kvstore.MemberChangeResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_pb_kvstore_proto_init() }
func file_pb_kvstore_proto_init() {
	if File_pb_kvstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pb_kvstore_proto_rawDesc), len(file_pb_kvstore_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_pb_kvstore_proto_goTypes,
		DependencyIndexes: file_pb_kvstore_proto_depIdxs,
		EnumInfos:         file_pb_kvstore_proto_enumTypes,
		MessageInfos:      file_pb_kvstore_proto_msgTypes,
	}.Build()
	File_pb_kvstore_proto = out.File
	file_pb_kvstore_proto_goTypes = nil
	file_pb_kvstore_proto_depIdxs = nil
}
